sudo: required # is required to use docker service in travis with superuser permissions
services:
  - docker # travis CI will automatically install a copy of docker into the environment

before_install:
  - docker build -t TashfikS/docker-react -f Dockerfile.dev . # build the image with the Dockerfile.dev

script:
  - docker run -e CI=true TashfikS/docker-react npm run test # run the test script in the container